# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Street', models.CharField(max_length=20)),
                ('District', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=18)),
            ],
        ),
    ]
