# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=10)),
                ('password2', models.CharField(blank=True, max_length=20)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
