# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180925_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformationdetails',
            old_name='password2',
            new_name='password',
        ),
    ]
