# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180925_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=40)),
                ('password', models.CharField(blank=True, max_length=20)),
                ('loginTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
