# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userinformationdetails_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdetails',
            name='successful',
            field=models.BooleanField(default=True),
        ),
    ]
