# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-25 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userinformationdetails_creationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformationdetails',
            name='creationTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Creation Time '),
            preserve_default=False,
        ),
    ]
