# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_logdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdetails',
            name='loginTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
